@startuml
skinparam style strictuml

class Prosumer {
  - prosumerId: String
  - prosumerDescription: String
  - pLoad: float[][]
  - ppvCapacity: float[][]
  + calculateSoc(): void
  + decideExchange(): void
}

class Profile {
  - profileId: String
  - profileTimeStamp: TimeStamp
  - profileValue: float
}

class Grid {
  - gridId: String
  - gridName: String
}

class GridExchange {
  - gridExchangeId: String
  - gridExchangeTimeStamp: TimeStamp
  - gridExchangeBuy: float
  - gridExchangeSell: float
  - gridExchangePriceBuy: float
  - gridExchangePriceSell: float
  + registerBuy(amount: float): void
  + registerSell(amount: float): void
}

class Community {
  - communityId: String
  - communityName: String
  - prosumers: Prosumer[*]
  + hasEnergy(): bool
  + needsEnergy(): bool
}

class CommunityExchange {
  - communityExchangeId: String
  - communityExchangeTimeStamp: TimeStamp
  - peerIn: float
  - peerOut: float
}

class PhotovoltaicPanel {
  - photovoltaicId: String
  - photovoltaicName: String
}

class PhotovoltaicEnergy {
  - photovoltaicEnergyId: String
  - photovoltaicEnergyTimeStamp: TimeStamp
  - pvLoad: float
  - pvBattery: float
}

class Battery {
  - batteryId: String
  - batteryName: String
  - capacityMax: float
  - efficiencyCharge: float
  - efficiencyDischarge: float
  - socMin: float
}

class BatteryEnergy {
  - batteryEnergyId: String
  - batteryEnergyTimeStamp: TimeStamp
  - stateOfCharge: float
  - charge: float
  - discharge: float
  - chargeBinary: bool
  - dischargeBinary: bool
}

class TimeStamp {
  - intervalOfTime: String
  - numberOfIntervals: int
}

' Relacionamentos '
Prosumer --> "1" Profile
Prosumer --> "1" PhotovoltaicPanel
Prosumer --> "1" Battery
Prosumer --> "1..*" GridExchange
Prosumer --> "1..*" CommunityExchange
PhotovoltaicPanel --> "1..*" PhotovoltaicEnergy
Battery --> "1..*" BatteryEnergy
Grid --> "1..*" GridExchange
Community --> "1..*" CommunityExchange
Community --> "1..*" Prosumer
PhotovoltaicEnergy --> "1" BatteryEnergy
Profile --> "1" TimeStamp
GridExchange --> "1" TimeStamp
CommunityExchange --> "1" TimeStamp
PhotovoltaicEnergy --> "1" TimeStamp
BatteryEnergy --> "1" TimeStamp

note right of Profile: Balance of the Prosumer in kW/h, positive values lead to buy energy from the grid
note right of BatteryEnergy: Charge and discharge constrained by efficiency and capacity

@enduml