@startuml
left to right direction

' Actors
actor Admin
actor User
actor Prosumer
actor "Community Manager" as CM
/' actor Grid
actor Solver '/

' Actor Relationships
Prosumer --|> User : <<extends>>
CM --|> User : <<extends>>

rectangle "Energy Community Platform" {

  ' Admin Use Cases
  package "Admin Management" {
    usecase "UC1: Create User" as UC1
    usecase "UC2: Update User" as UC2
    usecase "UC3: Delete User" as UC3
    usecase "UC4: Manage Roles and Permissions" as UC4
    usecase "UC5: Monitor Platform Usage" as UC5

    Admin --> UC1
    Admin --> UC2
    Admin --> UC3
    Admin --> UC4
    Admin --> UC5
  }

  ' User Use Cases
  package "Account Management" {
    usecase "UC6: Register Account" as UC6
    usecase "UC7: Update Account" as UC7
    usecase "UC8: Delete Account" as UC8
    usecase "UC9: Join Energy Community" as UC9

    User --> UC6
    User --> UC7
    User --> UC8
    User --> UC9
  }

  ' Prosumer Use Cases
  package "Energy Management for Prosumer" {
    usecase "UC10: Upload Energy Data" as UC10
    usecase "UC11: Update Energy Data" as UC11
    usecase "UC12: Analyse Energy Trends \n(define x, y values and relation)" as UC12
    usecase "UC13: View Consumption/Production History" as UC13
    /' usecase "UC14: Set Energy Usage Preferences" as UC14 '/
    /' usecase "UC15: Trade Energy with Community" as UC15 '/
    /' usecase "UC16: Optimize Energy Usage" as UC16 '/
    usecase "UC17: View Cost/Revenue from Trading" as UC17

    Prosumer --> UC10
    Prosumer --> UC11
    Prosumer --> UC12
    Prosumer --> UC13
/'     Prosumer --> UC14
    Prosumer --> UC15
    Prosumer --> UC16 '/
    Prosumer --> UC17
  }

  ' Community Manager Use Cases
  package "Community Management" {
    usecase "UC18: Create Energy Community" as UC18
    usecase "UC19: Add Community Data" as UC19
    usecase "UC20: Analyse Community Energy Balance" as UC20
    usecase "UC21: Delete Community Data" as UC21
    usecase "UC22: Manage Community Members" as UC22
    usecase "UC23: Generate Community Reports" as UC23
    usecase "UC24: Configure Energy Sharing Rules" as UC24
    usecase "UC25: Monitor Energy Sharing Efficiency" as UC25
    /' usecase "UC26: Set Community Energy Goals" as UC26 '/

    CM --> UC18
    CM --> UC19
    CM --> UC20
    CM --> UC21
    CM --> UC22
    CM --> UC23
    CM --> UC24
    CM --> UC25
/'     CM --> UC26 '/
  }


}

@enduml