@startuml 
left to right direction

actor Admin
actor User
actor Prosumer
actor "Community Manager" as CM



 
rectangle "Energy Community Platform" {
  usecase "Create users" as UC1
  usecase "Update users" as UC2
  usecase "Delete users" as UC3

  usecase "Register account" as UC4
  usecase "Update account" as UC5
  usecase "Delete account" as UC6

  usecase "Upload data" as UC7
  usecase "Update data" as UC8
  usecase "Analyse data" as UC9

  usecase "Create energy community" as UC10
  usecase "Add Data" as UC11
  usecase "Delete Data" as UC12
    
    Admin --> UC1
    Admin --> UC2
    Admin --> UC3

    User --> UC4
    User --> UC5
    User --> UC6

    Prosumer --> UC7
    Prosumer --> UC8
    Prosumer --> UC9

    CM --> UC10
    CM --> UC11
    CM --> UC9
    CM --> UC12
}
@enduml
