@startuml 

' Diagrama de Caso de Uso
left to right direction
actor Prosumer
actor Grid
actor Solver

rectangle "Optimization System" {
    usecase "Load input data" as UC1
    usecase "OPtimize uso of energy" as UC2
    usecase "Buy/Sell Energy" as UC3
    usecase "Trade energy between prosumers" as UC4
}

Prosumer -- UC1
Prosumer -- UC2
Prosumer -- UC3
Prosumer -- UC4
Grid -- UC3
Solver -- UC2

@enduml
