@startuml  

' Diagrama de Caso de Uso
left to right direction
actor Prosumer
actor Admin
actor CommunityManager

rectangle "Optimization System" {
    usecase "Load input data" as UC1
    usecase "Manage user account" as UC2
    usecase "Manage Users" as UC3
    usecase "Manage input data" as UC4
    usecase "Analyse output data" as UC5
    usecase "Manage Users Permissions" as UC6
    
}

Prosumer -- UC1
Prosumer -- UC2
Prosumer -- UC3
Prosumer -- UC4
Prosumer -- UC5

Admin -- UC3
Admin -- UC6

CommunityManager -- UC2
CommunityManager -- UC5

@enduml