version: 2
jobs:
  build:
    docker:
       - image: circleci/node:20.19.0
         environment:
           MONGO_URI: mongodb://mongo:27017/test
       - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test