@startuml
actor "Admin" as A
participant "System" as Sys

A -> Sys: 1: Starts pacient creation
Sys --> A: 1.1: ask for pacient data (first name, last name, date of birth, contact information)

A -> Sys: 2: input the data requested
Sys --> A: 2.1: sucess operation
@enduml
