@startuml

' Diagrama de Classes
class Prosumer {
    - PLoad: float[]
    - PPV_capacity: float[]
    - SOC: float
    - P_buy: float
    - P_sell: float
    + otimizarEnergia()
}

class Grid {
    - Cbuy: float[]
    - Csell: float[]
    + fornecerEnergia()
    + comprarEnergia()
}

class Solver {
    + resolverProblema()
}

Prosumer --> Grid : Compra/Vende Energia
Prosumer --> Prosumer : Troca Energia P2P
Prosumer --> Solver : Envia Modelo
Solver --> Prosumer : Retorna Resultados

@enduml
