import {
  ProfileDTO,
  IStorageEfficiency,
  IP2PEnergyFlow,
  ICommunityEnergy,
  IConsumptionDistribution,
  IProfileCluster,
} from '../../interfaces';

export const profileData: ProfileDTO[] = [
  // Current period (2025-06-01 to 2025-06-02)
  // Prosumer 1
  {
    prosumerId: 'prosumer1',
    date: '2025-06-01',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '80',
    energyCharge: '20',
    energyDischarge: '10',
    photovoltaicEnergyLoad: '50',
    boughtEnergyAmount: '30',
    boughtEnergyPrice: '0.15',
    soldEnergyAmount: '12',
    soldEnergyPrice: '0.14',
    peerOutputEnergyLoad: '10',
    peerOutPrice: '0.13',
    peerInputEnergyLoad: '5',
    peerInPrice: '0.12',
    profileLoad: '120',
  },
  {
    prosumerId: 'prosumer1',
    date: '2025-06-02',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '85',
    energyCharge: '25',
    energyDischarge: '15',
    photovoltaicEnergyLoad: '60',
    boughtEnergyAmount: '50',
    boughtEnergyPrice: '0.16',
    soldEnergyAmount: '20',
    soldEnergyPrice: '0.15',
    peerOutputEnergyLoad: '8',
    peerOutPrice: '0.14',
    peerInputEnergyLoad: '6',
    peerInPrice: '0.13',
    profileLoad: '150',
  },
  // Prosumer 2
  {
    prosumerId: 'prosumer2',
    date: '2025-06-01',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '60',
    energyCharge: '15',
    energyDischarge: '8',
    photovoltaicEnergyLoad: '45',
    boughtEnergyAmount: '25',
    boughtEnergyPrice: '0.15',
    soldEnergyAmount: '10',
    soldEnergyPrice: '0.14',
    peerOutputEnergyLoad: '5',
    peerOutPrice: '0.13',
    peerInputEnergyLoad: '10',
    peerInPrice: '0.12',
    profileLoad: '100',
  },
  {
    prosumerId: 'prosumer2',
    date: '2025-06-02',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '65',
    energyCharge: '20',
    energyDischarge: '10',
    photovoltaicEnergyLoad: '50',
    boughtEnergyAmount: '40',
    boughtEnergyPrice: '0.16',
    soldEnergyAmount: '15',
    soldEnergyPrice: '0.15',
    peerOutputEnergyLoad: '6',
    peerOutPrice: '0.14',
    peerInputEnergyLoad: '8',
    peerInPrice: '0.13',
    profileLoad: '130',
  },
  // Prosumer 3
  {
    prosumerId: 'prosumer3',
    date: '2025-06-01',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '70',
    energyCharge: '18',
    energyDischarge: '12',
    photovoltaicEnergyLoad: '55',
    boughtEnergyAmount: '35',
    boughtEnergyPrice: '0.15',
    soldEnergyAmount: '15',
    soldEnergyPrice: '0.14',
    peerOutputEnergyLoad: '7',
    peerOutPrice: '0.13',
    peerInputEnergyLoad: '4',
    peerInPrice: '0.12',
    profileLoad: '110',
  },
  {
    prosumerId: 'prosumer3',
    date: '2025-06-02',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '75',
    energyCharge: '22',
    energyDischarge: '14',
    photovoltaicEnergyLoad: '65',
    boughtEnergyAmount: '45',
    boughtEnergyPrice: '0.16',
    soldEnergyAmount: '18',
    soldEnergyPrice: '0.15',
    peerOutputEnergyLoad: '9',
    peerOutPrice: '0.14',
    peerInputEnergyLoad: '5',
    peerInPrice: '0.13',
    profileLoad: '140',
  },
  // Previous period (2025-05-30 to 2025-05-31, simulated)
  // Prosumer 1
  {
    prosumerId: 'prosumer1',
    date: '2025-05-30',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '78',
    energyCharge: '18',
    energyDischarge: '9',
    photovoltaicEnergyLoad: '45',
    boughtEnergyAmount: '33',
    boughtEnergyPrice: '0.14',
    soldEnergyAmount: '10',
    soldEnergyPrice: '0.13',
    peerOutputEnergyLoad: '5',
    peerOutPrice: '0.12',
    peerInputEnergyLoad: '4',
    peerInPrice: '0.11',
    profileLoad: '108',
  },
  {
    prosumerId: 'prosumer1',
    date: '2025-05-31',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '82',
    energyCharge: '23',
    energyDischarge: '11',
    photovoltaicEnergyLoad: '55',
    boughtEnergyAmount: '55',
    boughtEnergyPrice: '0.15',
    soldEnergyAmount: '17',
    soldEnergyPrice: '0.14',
    peerOutputEnergyLoad: '10',
    peerOutPrice: '0.13',
    peerInputEnergyLoad: '5',
    peerInPrice: '0.12',
    profileLoad: '135',
  },
  // Prosumer 2
  {
    prosumerId: 'prosumer2',
    date: '2025-05-30',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '58',
    energyCharge: '14',
    energyDischarge: '7',
    photovoltaicEnergyLoad: '40',
    boughtEnergyAmount: '28',
    boughtEnergyPrice: '0.14',
    soldEnergyAmount: '8',
    soldEnergyPrice: '0.13',
    peerOutputEnergyLoad: '4',
    peerOutPrice: '0.12',
    peerInputEnergyLoad: '7',
    peerInPrice: '0.11',
    profileLoad: '90',
  },
  {
    prosumerId: 'prosumer2',
    date: '2025-05-31',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '62',
    energyCharge: '18',
    energyDischarge: '9',
    photovoltaicEnergyLoad: '45',
    boughtEnergyAmount: '44',
    boughtEnergyPrice: '0.15',
    soldEnergyAmount: '13',
    soldEnergyPrice: '0.14',
    peerOutputEnergyLoad: '5',
    peerOutPrice: '0.13',
    peerInputEnergyLoad: '6',
    peerInPrice: '0.12',
    profileLoad: '117',
  },
  // Prosumer 3
  {
    prosumerId: 'prosumer3',
    date: '2025-05-30',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '68',
    energyCharge: '16',
    energyDischarge: '10',
    photovoltaicEnergyLoad: '50',
    boughtEnergyAmount: '38',
    boughtEnergyPrice: '0.14',
    soldEnergyAmount: '13',
    soldEnergyPrice: '0.13',
    peerOutputEnergyLoad: '6',
    peerOutPrice: '0.12',
    peerInputEnergyLoad: '4',
    peerInPrice: '0.11',
    profileLoad: '99',
  },
  {
    prosumerId: 'prosumer3',
    date: '2025-05-31',
    intervalOfTime: '00:00-23:59',
    numberOfIntervals: 24,
    stateOfCharge: '72',
    energyCharge: '20',
    energyDischarge: '12',
    photovoltaicEnergyLoad: '60',
    boughtEnergyAmount: '50',
    boughtEnergyPrice: '0.15',
    soldEnergyAmount: '15',
    soldEnergyPrice: '0.14',
    peerOutputEnergyLoad: '8',
    peerOutPrice: '0.13',
    peerInputEnergyLoad: '4',
    peerInPrice: '0.12',
    profileLoad: '126',
  },
];

export const storageEfficiencyData: IStorageEfficiency[] = [
  { prosumer: 'Prosumer 1', efficiency: 85 },
  { prosumer: 'Prosumer 2', efficiency: 78 },
  { prosumer: 'Prosumer 3', efficiency: 82 },
];

export const p2pEnergyFlowData: IP2PEnergyFlow[] = [
  { source: 'Prosumer 1', target: 'Prosumer 2', value: 10 },
  { source: 'Prosumer 1', target: 'Prosumer 3', value: 5 },
  { source: 'Prosumer 2', target: 'Prosumer 3', value: 8 },
];

export const communityEnergyData: ICommunityEnergy[] = [
  { community: 'Community A', generated: 450, traded: 200 },
  { community: 'Community B', generated: 350, traded: 150 },
  { community: 'Community C', generated: 400, traded: 100 },
];

export const consumptionDistributionData: IConsumptionDistribution[] = [
  { intervals: '0-5', count: 10 },
  { intervals: '5-10', count: 15 },
  { intervals: '10-15', count: 20 },
  { intervals: '15-20', count: 12 },
  { intervals: '20-25', count: 8 },
];

export const profileClusterData: IProfileCluster[] = [
  { prosumer: 'Prosumer 1', x: 1.2, y: 2.5 },
  { prosumer: 'Prosumer 2', x: 1.8, y: 1.9 },
  { prosumer: 'Prosumer 3', x: -0.5, y: 0.8 },
];