@startuml

autonumber

Actor User
activate User
User -> SPA : Get a list of all the patients

activate SPA


SPA -> Patient : GET/patients/findAll
activate Patient

Patient --> SPA : status code
deactivate Patient

alt successfull case
    SPA --> User : Returns requested list
else failure
    SPA --> User : Does not return requested list
end


@enduml
