@startuml
'https://plantuml.com/component-diagram



package "Frameworks & Drivers" {
    component Database
    component Routing
}

component DTO
component Data_Model

Database -- Data_Model_API
Database -- Database_Driver_API
Data_Model_API - Data_Model
Routing -- DTO_API
Routing -- Controller_API
DTO_API - DTO


package "Interface Adapters"{
    component Repositories
    component Controllers
}

Controller_API -- Controllers
DTO_API -- Controllers
Data_Model_API -- Repositories
Database_Driver_API -- Repositories
Controllers -- Service_API
Repositories -- Repo_API
Repositories -- Model_API
'Controllers -- VO_API
'Repositories -- VO_API

package "Application Business Rules"{
    component Services
}

'VO_API -- Services
Service_API -- Services
Repo_API -- Services
Services -- Model_API

package "Enterprise Business Rules"{
    component Domain
}

'VO_API -- Domain
Model_API -- Domain




@enduml