@startuml 

interface API_Optimization
interface API_Exterior


component "BackEnd" {
    component DB
    component Server
    port P1
    port P2
}

API_Optimization -- P1
API_Exterior -- P2
P1 - Server
P2 - Server
Server -(0- DB

@enduml
