@startuml

autonumber

Actor User
activate User
User -> SPA : Edit a patient information
activate SPA

SPA --> User : Shows patients id and name list 
deactivate SPA

User -> SPA : types patient id
activate SPA

SPA -> Patient : PUT/PATCH/patient/{firstName, lastName, phoneNumber, email, emergencyContact,}
activate Patient


Patient -> ContactInformation : Update phoneNumber, email
activate ContactInformation

ContactInformation --> Patient : Status of update
deactivate ContactInformation

Patient --> SPA : Status code (200/400/500)
deactivate Patient

alt successful case
    SPA --> User : Patient updated successfully (200)
else failure
    SPA --> User : Patient not updated (400/500)
end

deactivate SPA
deactivate User


@enduml
