@startuml update1
skinparam Monochrome true
skinparam PackageStyle rectangle
skinparam Shadowing false

title Sequence Diagram: PUT/PATCH Level 1

actor "User" as User
participant "SATCOMM System" as System

activate User
User -> System : 1 : Initiates entity update process
activate System
System --> User : 1.1 : Provides list of entities
deactivate System
User -> System : 2 : Selects entity to update
activate System
System --> User : 2.1 : Requests updated entity data
deactivate System
User -> System : 3 : Submits updated data
activate System
System --> User : 3.1 : Displays success confirmation and updated entity details
deactivate System

@enduml