@startuml
    package "Photovoltaic Panel"{
        object p_pv_load as "Photovoltaic Load"{
            * P_Pv_Load()
        }
    }
    
    package "Prosumer"{
        object P as "Prosumer Load"{
            * P_Load()
        }
    }
   

    package "Battery" {
        object b_ch as "Charge"{
            * Ess_Charge()
        }

        object b_dch as "Discharge"{
            * Ess_Discharge()
        }
    }

    package "Grid" {
        object g_buy as "Buy energy"{
            * P_Buy()
        }
        object g_sell as "Sell energy"{
            * P_Sell()
        }
    }

    package "Community" {
        object peer_out as "Send energy"{
            * Peer_Out()
        }
        object peer_in as "Receive energy"{
            * Peer_In()
        }
    }
    diamond dia1
    diamond dia2
    diamond dia3
    p_pv_load --> P: "Prosumer is consuming energy"
    p_pv_load --> b_ch: "Prosumer is not consuming energy"
    b_dch --> dia1
    peer_out --> dia1
    g_buy --> dia1
    dia1 --> P: "Prosumer needs more energy"
    b_dch --> dia2
    p_pv_load --> dia2
    dia2 --> peer_in: "Community needs energy"
    p_pv_load --> dia3
    b_dch --> dia3
    dia3 --> g_sell: "Best case, nobody needs energy"
@enduml